name: ossa
description: A simple package for working with multithreading, using an interface similar to tasks in C#.
version: 1.0.4
repository: https://github.com/GlebBatykov/ossa

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
